---
sudo: required
services: [ docker ]

before_install: rm Gemfile.lock || true
cache: bundler

language: ruby

script: bundle exec rake $DO
env:
  - BEAKER_PUPPET_COLLECTION=puppet6

jobs:
  include:
    - stage: validate
      env:
        - DO=validate_all
        - PUPPET='~> 4'
    - env:
        - DO=validate_all
        - PUPPET='~> 5'
    - env:
        - DO=validate_all
        - PUPPET='~> 6'
    - stage: unit
      env:
        - DO=spec
        - PUPPET='~> 4'
    - env:
        - DO=spec
        - PUPPET='~> 5'
    - env:
        - DO=spec
        - PUPPET='~> 6'
    - stage: acceptance
      env:
        - DO=beaker
        - BEAKER_set=ubuntu_1404
    - env:
        - DO=beaker
        - BEAKER_set=ubuntu_1604
    - env:
        - DO=beaker
        - BEAKER_set=ubuntu_1804
    - env:
        - DO=beaker
        - BEAKER_set=debian_8
    - env:
        - DO=beaker
        - BEAKER_set=centos_7
    - stage: deploy
      script: true
      env:
        - DEPLOY_TO_FORGE=yes

deploy:
  provider: puppetforge
  user: pegas
  password:
    secure: "NRcc1F8jHGQ+JCY0GaYtVWveK87glIvXkcMMPfiT5aIbZBW/eA2OfM/kS/iXgkZ3NhoUH6xKrNuCcpmnFit8eq52yJhNKKbXR4tON49PITEergQzEY+kyTtAJUM27JGJVf7RCdwZj+xiMe1OVJbGkDdptgRxH94R6el+2mdUDiGW6clpaypFEGI6642XmHOhd1trA/KWpha2Pwa+M65YLx4wSpdSqkZ82yO5q0z49BF0gtrhJjv5HH7O3Lv8BRLmPh9dgkyR5xUOZfjvkn2G5Kpwb6SMWlRqEGWZKS6i87F0w2z00pD0h0Hi3ZeFRFqFzYfzSJt2RwG+jpLWAIVDOr4gEFTUgaDb9N+hzsC51nmrgnhoyiZg6j8zP7L8w6LTDfzQXjPmNHdGNcwvPvkbEEThbM46Sko4F7RvLM9WRJpJ4m9MVboXSOLB3H6UuVtnlCJwEGL4xd72BFdVWusmg3ZguyY3INuIWFBBWQNBgTWvPqM1/omd3x3NhlLByoKWWy/fe6U1zzl1Vfcj8EsKNTdW6/e38foj8qpqorDCfjZHBuaku2qfI+vH8jS78d8w9CVkYgMyxCeIdePTHe3k+SpSLa648uDRXqdPk4FFS1yNknWAMQLr2vwasx4htBOK+TYp1BopcrsBgkWMMhzVkJPwM6uyXUfiyHZftl/Q+eE="
  on:
    tags: true
    all_branches: false
    condition: "$DEPLOY_TO_FORGE = yes"
