---
language: ruby
install:
- bundle install --path .bundle/gems --without acceptance
- bundle exec librarian-puppet install --path .dependencies
script: bundle exec rake validate spec
rvm: 2.3.1
sudo: false
env:
- PUPPET=4.4.1
- PUPPET=4.9.1
